### PR TITLE
[Module] Update lib/module, Improve test printing

### PR DESCRIPTION
**Pull request by Hazurl**

### CODE REVIEW

**Comment by Jackojc** [comment]
Why not update the submodule using `git submodule update --remote --merge`?

**Comment by Hazurl** [comment]
Wdym ?

**Comment by Jackojc** [comment]
Updates it without needing a commit I believe.

**Comment by Hazurl** [comment]
That seems to do a commit 🤔 
Anyway, do you approve this PR ?

**Pull request merged**
